name: Daily Sync _worker.js from cmliu/edgetunnel

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 零点运行
  workflow_dispatch:      # 手动触发

jobs:
  update-worker:
    runs-on: ubuntu-latest

    steps:
      - name: 检出当前仓库代码
        uses: actions/checkout@v3

      - name: 获取上游仓库最新 commit 哈希
        id: upstream
        run: |
          UPSTREAM_COMMIT=$(git ls-remote https://github.com/cmliu/edgetunnel.git HEAD | awk '{print $1}')
          echo "upstream_commit=$UPSTREAM_COMMIT" >> $GITHUB_OUTPUT

      - name: 读取上次同步的 commit 哈希（如有）
        id: local
        run: |
          if [ -f .last_upstream_commit ]; then
            LAST_COMMIT=$(cat .last_upstream_commit)
          else
            LAST_COMMIT=""
          fi
          echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT

      - name: 判断是否需要更新
        id: check
        run: |
          if [ "${{ steps.upstream.outputs.upstream_commit }}" != "${{ steps.local.outputs.last_commit }}" ]; then
            echo "need_update=true" >> $GITHUB_OUTPUT
          else
            echo "need_update=false" >> $GITHUB_OUTPUT
          fi

      - name: 克隆上游并提取文件
        if: steps.check.outputs.need_update == 'true'
        run: |
          git clone --depth=1 https://github.com/cmliu/edgetunnel.git upstream_repo
          cp "upstream_repo/明文源码.js" new_worker.js

      - name: 比较文件并更新
        if: steps.check.outputs.need_update == 'true'
        run: |
          if [ ! -f "_worker.js" ]; then
            echo "首次同步"
            mv new_worker.js _worker.js
            echo "updated=true" >> $GITHUB_ENV
          elif ! cmp -s new_worker.js _worker.js; then
            echo "文件内容有变动"
            mv new_worker.js _worker.js
            echo "updated=true" >> $GITHUB_ENV
          else
            echo "文件内容无变动"

      - name: 保存最新 commit 哈希
        if: env.updated == 'true' || steps.check.outputs.need_update == 'true'
        run: |
          echo "${{ steps.upstream.outputs.upstream_commit }}" > .last_upstream_commit

      - name: 提交 _worker.js 变更（如果有）
        if: env.updated == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js .last_upstream_commit
          git commit -m "自动同步 _worker.js 来自 cmliu/edgetunnel"
          git push

      - name: 自动创建并提交 wrangler.toml（仅当 _worker.js 有变更）
        if: env.updated == 'true'
        run: |
          TODAY=$(date -u +%F)
          echo "name = \"edgetunnel-automatico\"" > wrangler.toml
          echo "type = \"javascript\"" >> wrangler.toml
          echo "compatibility_date = \"$TODAY\"" >> wrangler.toml

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wrangler.toml
          git commit -m "自动创建 wrangler.toml（含 $TODAY）"
          git push
