name: Daily Sync _worker.js from cmliu/edgetunnel

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 零点运行
  workflow_dispatch:      # 手动触发

jobs:
  update-worker:
    runs-on: ubuntu-latest

    steps:
      - name: 检出当前仓库代码
        uses: actions/checkout@v3

      - name: 下载最新 edgetunnel 明文源码.js
        run: |
          curl -L -o new_worker.js https://raw.githubusercontent.com/cmliu/edgetunnel/main/%E6%98%8E%E6%96%87%E6%BA%90%E7%A0%81.js

      - name: 比较差异，仅在有更新时才替换
        run: |
          if [ ! -f "_worker.js" ]; then
            echo "首次下载，直接同步"
            mv new_worker.js _worker.js
            echo "updated=true" >> $GITHUB_ENV
          elif ! cmp -s new_worker.js _worker.js; then
            echo "发现内容更新，准备同步"
            mv new_worker.js _worker.js
            echo "updated=true" >> $GITHUB_ENV
          else
            echo "无内容更新"
          fi

      - name: 提交变更（如果有）
        if: env.updated == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js
          git commit -m "自动同步 _worker.js 来自 cmliu/edgetunnel" || echo "无变更可提交"
          git push
